### ISSUE TITLE
flag '#' results in undefined behavior with 'd' conversion specifier

### ISSUE THREAD

**Issue by dmalan** [cs50/help50#65] opened 2016-09-10 18:16 UTC
```
mario.c:19:24: error: flag '#' results in undefined behavior with 'd' conversion specifier [-Werror,-Wformat]
            printf("% ## *d\n", h-2+i , 0);
                    ~~~^~~~
1 error generated.
make: *** [mario] Error 1
```

**Comment by brianyu28** [comment] 2016-09-18 13:07
Duplicate of #67, closing this one.

**Closed by brianyu28** 2016-09-18 13:07 UTC
Labels: enhancement
